### ISSUE TITLE
Adapter Enabled|Disabled

### ISSUE THREAD

**Issue by BarnumD** [dsccommunity/HyperVDsc#136]
In xHyper-V or xNetworking DSC, how do we ensure that an adapter is enabled or disabled?  (In the windows gui, right click the adapter and select disable|enable.)  The question applies to both physical and virtual adapters.  Does this functionality currently exist?

**Comment by johlju** [comment]
For NetworkingDsc you have the  `Status` parameter for [NetAdapterName]([https://github.com/PowerShell/NetworkingDsc/wiki/NetAdapterName). xVMNetworkAdapter doesn't seem to have such parameter.

**Comment by johlju** [comment]
There is no enable or disable button in the GUI for a VM Network Adapter, so if the network adapter should not be used it should be removed entirely. Disabling a net adapter inside Windows the NetAdapterName resource in NetworkingDsc should be used.
