### ISSUE TITLE
xNewVMHostName, xNewVMIPAddress: Customize hostname and IP address rules for newly created VMs

### ISSUE THREAD

**Issue by krishdevan** [dsccommunity/HyperVDsc#187]
### Description
After creating the new VM using the xVMHyperV, there is no way to customize the new VM's Computer name (aka hostname). There is a switch for 'WaitForIP' but it assumes presence of a DHCP. The ability to customize the IP address info on each VM created would be great.

### Proposed properties
xNewVMHostName - ability to rename the computer to a custom name
xNEWVmIpaddress - something similar to xNetworking where you can set static IP/prefix/Gw/DNS address info on the new VM created.

**Comment by johlju** [comment]
For the IP address I think we could use the existing resource [`VMNetworkAdapter`](https://github.com/dsccommunity/HyperVDsc/wiki/VMNetworkAdapter)?

To customize the hostname inside a VM I think we should use the https://github.com/dsccommunity/NetworkingDsc/wiki (or if there is no resource for it, extend that module instead).

Closing this issue as it looks like this should already be supported. Please reopen if I have misunderstood something. 🙂
