### ISSUE TITLE
Convert xHyper-V to HQRM standards

### ISSUE THREAD

**Issue by PlagueHO** [dsccommunity/HyperVDsc#62]
This does not necessarily require renaming this module to HQRM naming but this module should be updated to bring it inline with current HQRM standards.

This should include Integration tests (even if they can't be run on AppVeyor).

**Comment by rchaganti** [comment]
Converting the resources in this module to HQRM isn't a very easy task. Also, I have many other resources in cHyper-V at the moment. So, there has to be a consolidated effort to make this module HQRM complaint. To that extent, I started a new repository in my account.

[https://github.com/rchaganti/HyperVDsc](https://github.com/rchaganti/HyperVDsc)

I have taken this path after carefully reviewing what we have here and the complexity in splitting the resources into more granular resources and make them HQRM compliant. Instead, it will be easy to write some of these from scratch. 

I have added a list of resources to the [README](https://github.com/rchaganti/HyperVDsc/blob/dev/README.md) (my wishlist + what I already have). There are 27 so far and I already have a bunch of them in progress. I have a Kanban for this project at [https://waffle.io/rchaganti/HyperVDsc](https://waffle.io/rchaganti/HyperVDsc).

I am going to seek community to come forward to create the resources that do not exist today.

Do let me know your thoughts on this. I will start pushing what I have starting next week. I will setup AppVeyor tests and build checks once I have the DSC resources being added to the repository.

**Comment by bgelens** [comment]
Pinging @PlagueHO @iainbrighton 

Would it be easier to create **HyperVDsc** (liking this on better personally) or **Hyper-VDsc** as a new module  instead of converting xHyper-V? 

And would you guys join @rchaganti as contributors if you like what he is proposing?

**Comment by iainbrighton** [comment]
@bgelens @PlagueHO @rchaganti Happy to help out and starting again will certainly be easier with one or two of those resources. I think that getting a list of required resources listed in some form of priority order needs to be done first? Once that's done we can all agree on schemas. Thoughts?

**Comment by rchaganti** [comment]
Yes. I have a wish list that I am working towards. 
[https://waffle.io/rchaganti/HyperVDsc](https://waffle.io/rchaganti/HyperVDsc)

You can see good to have and must have resources as per my requirements at the moment. We can work on this ordering. I have a bunch of them already in progress including the resources from my cHyper-V.
